name: flutter_camera_app
description: A flutter application that demonstrate how to add camera to flutter and share captured image file.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.5.2+1
  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  dio: ^3.0.10
  http: any
  image_picker: ^0.6.6+5
  flutter_launcher_icons: "^0.8.0"

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/medicine.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher_round.png"
  
