name: flutter_camera_app
description: A flutter application that demonstrate how to add camera to flutter and share captured image file.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.2
  camera: ^0.8.1
  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  dio: ^3.0.9
  flutter_launcher_icons: "^0.8.0"
  syncfusion_flutter_calendar: ^18.3.51
  add_2_calendar: ^1.4.0
  table_calendar: ^2.3.3
  shared_preferences: ^0.5.12+4
  flutter_spinkit: ^4.1.2
  introduction_screen: ^1.0.9
  flutter_easyloading: ^2.2.2
  flutter_webview_plugin: ^0.3.11
  commons: ^0.7.8+3
  connection_status_bar: ^1.1.4
  video_player: ^2.0.2
  recase: ^3.0.1
  flutter_exif_rotation: ^0.4.1
  exif:


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/medicine.png
    - assets/splash_1.png
    - assets/splash_2.png
    - assets/splash_3.png
    - assets/image1.png
    - assets/company_logo.png
    - assets/question.png
    - assets/logo.png
    - assets/example.mp4

  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/ic_medicine.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher_round.png"
  
  