# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thesis_2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thesis_2020

  target 'Thesis_2020Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Thesis_2020UITests' do
    # Pods for testing
  end
 pod "Alamofire"

end
